name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 to use the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3 to use the latest version
        with:
          node-version: '20'  # Using Node.js 20 as the latest LTS version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Ensure using the correct version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
